### ISSUE TITLE
Stable package on packagist doens't work with PHP7

### ISSUE THREAD

**Issue by mfn** [farafiri/PHP-parsing-tool#11]
The latest stable published version is 1.0.1 which was cut from this tag: https://github.com/farafiri/PHP-parsing-tool/releases/tag/v1.0.1 on 2017-02-11

The fix for PHP7 class was merged on 2017-02-24.

Since no new release was published, the packagist version doesn't include this fix.

**Comment by farafiri** [comment]
I ll do it after issue #18
