### ISSUE TITLE
Is there a way to generate a string that conforms to your CFG specification syntax from a BGF file?

### ISSUE THREAD

**Issue by humanitiesclinic** [farafiri/PHP-parsing-tool#37]
Hi

Relating to the other issue, one of the reasons why there was a problem/error was that the BNF string was problematic. I actually got it from: https://gist.github.com/arslancharyev31/c48d18d8f917ffe217a0e23eb3535957
and modified it. Guess that was insufficient.

Can I ask, do you have a language spec of the C language that conforms to your CFG spec syntax?

**Comment by humanitiesclinic** [comment]
(That also includes the lexical grammar in it, not just the phase structure grammar)

**Comment by humanitiesclinic** [comment]
*phrase

**Comment by farafiri** [comment]
No, there is no easy way to conver your BGF file into this lib standard.
You can try with regex replacements like replacing | to :=> and ::= to :=>
(in editor with regex support:
(\n\s+)[|]\s into $1:=>\s
\r\n\r\n([a-zA-Z0-9_-]+)\s::= into .\r\n\r\n$1 :=>
)

but there is more problems with file you provided, for example:
1. A lot of undefined tokens eg. sizeof enum etc.
2. incorrect ';' support: note that there is no semicolon betwen external-declaration -s but in c those semicolons are required.
3. Note:
struct-declarator-list ::= struct-declarator
                           | struct-declarator-list ',' struct-declarator
struct field should be separated by ; (not by ,)

I stopped digging here but I assure you - there is more problems with this bnf.

**Comment by humanitiesclinic** [comment]
Ok, do u have a separate language spec of the C language that conforms to your CFG spec syntax?

**Comment by farafiri** [comment]
No, I don't.
