### ISSUE TITLE
Can I use this tool to generate strings as output from a context-free grammar as input?

### ISSUE THREAD

**Issue by humanitiesclinic** [farafiri/PHP-parsing-tool#38]
Can I use this tool to generate strings as output from a context-free grammar as input?

**Comment by humanitiesclinic** [comment]
Or can it only be used for parsing?

**Comment by humanitiesclinic** [comment]
any answer?

**Comment by mfn** [comment]
You're question is _really very low_ on detail.

Please provide more context what you're after, what you're trying.

Thanks

**Comment by farafiri** [comment]
Hello,
Short answer: No, You cant generate string.
Longer answer: In first stage of development I created such a functionality. However it was hard to test and its cost >> benefit, and its generally imposible to do that if grammar uses contex checking, for example x :=> ?/(a|b)+/ /(b|c)+/. If your grammar uses only branches with string litterals then it may work. (this code is present only in first commit in repository).

**Comment by humanitiesclinic** [comment]
ok noted tq
