### ISSUE TITLE
Error with parsing grammar

### ISSUE THREAD

**Issue by humanitiesclinic** [farafiri/PHP-parsing-tool#40]
I have this grammar:

start :=> translation_unit.
translation_unit :=> external_declaration
:=> translation_unit external_declaration.
external_declaration :=> function_definition
:=> declaration.
function_definition :=> declaration_specifiers declarator declaration_list? compound_statement.
declaration_list :=> declaration
:=> declaration_list declaration.
statement :=> labeled_statement
:=> compound_statement
:=> expression_statement
:=> selection_statement
:=> iteration_statement
:=> jump_statement.
labeled_statement :=> identifier ":" statement

I am getting this error:

Fatal error: Uncaught ParserGenerator\Exception: Given grammar is incorrect:
line: 17, character: 33
expected: rules or sequence or ItemRestrictionsPlugin_condition or  or  or /(\*{1,2}|\+{1,2}|\?{1,2})/ or /(\*{1,2}|\+{1,2}|\?{1,2})/ or "<" or possibleRuleCondition or "" or /\./ or /\.?/
found:  ":" statement

Why is ":" causing a problem, and how can I solve this?

**Comment by farafiri** [comment]
I don't know. After pasting it i have following error:
PHP Fatal error:  Uncaught ParserGenerator\Exception: Grammar definition error: Undefined branch [declaration] in C:\Users\user\Documents\GitHub\PHP-parsing-tool\src\GrammarParser.php:268

which is exactly what I would expect.

Check if in ":" those characters around colon are  double-quotes (there are a lot of characters similar to double-quote in utf http://unicode.org/cldr/utility/confusables.jsp?a=%22&r=None)

**Comment by humanitiesclinic** [comment]
Issue resolved. I finally found that the space just before ":" is not the usual ASCII space...
